name: Release Validation

on:
  release:
    types: [published]

jobs:
  validate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check manifest version matches tag
        run: python scripts/check_version.py ${{ github.ref_name }}

      - name: Run HassFest
        uses: home-assistant/actions/hassfest@master

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: "integration"
